# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Datadog Agent
        uses: datadog/agent-github-action@v1
        with:
            api_key: ${{ secrets.DD_API_KEY }}      
      - run: |
          pip install -U pytest
          pip install -U ddtrace
          DD_ENV=ci DD_SERVICE=nick-test pytest --ddtrace

      # - uses: actions/checkout@v2
      # - name: test
      #   run: |
      #     pip install -U pytest
      #     pip install -U ddtrace
      #     DD_ENV=ci DD_SERVICE=NICK-TEST pytest --ddtrace
          
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
