name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Datadog Agent
        uses: datadog/agent-github-action@v1
        with:
            api_key: ${{ secrets.DD_API_KEY }}      

      - uses: actions/checkout@v2
      - name: test
        run: |
          pip install -U pytest
          pip install -U ddtrace
          DD_ENV=ci DD_SERVICE=NICK-TEST pytest --ddtrace
          
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.