name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: a
        name: Datadog Agent
        # uses: DataDog/agent-github-action@v1
        # with:
        #     api_key: ${{ secrets.DD_API_KEY }}
        #     datadog_site: "us3.datadoghq.com"
        run: echo "Hello World!"
      - uses: actions/checkout@v2

      - id: b
        name: PreBuild
        run: |
          sudo apt-get install jq python3.8
          sleep 5

      - id: c
        name: Build 
        run: |
          curl -H "Accept:application/vnd.github.v3+json" https://api.github.com/repos/nicksre/nick-test/actions/runs/${{ github.run_id}}/jobs | jq ".jobs[0].steps[2]" >> out.json
          cat out.json

      - id: d
        name: Print value
        run: |
          pwd && ls
          a=$(jq ".started_at" out.json)
          b=$(jq ".completed_at" out.json)
          echo $a ; echo $b
          python3 timediff.py $a $b

      # - uses: actions/checkout@v2
      # - id: c
      #   name: Test
      #   run: |
      #     pip install -U pytest
      #     pip install -U ddtrace
      #     DD_ENV=ci DD_SERVICE=NICK-TEST pytest --ddtrace

      # - id: d
      #   name: Count
      #   uses: masci/datadog@v1
      #   with:
      #     api-key:  ${{ secrets.DD_API_KEY }}
      #     api-url: https://us3.datadoghq.com
      #     metrics: |
      #       - type: "count"
      #         name: "test.runs.count"
      #         value: 1.0
      #         host: ${{ github.repository_owner }}
      #         tags:
      #           - "project:${{ github.repository }}"
      #           - "branch:${{ github.head_ref }}"

      # - id: e
      #   name: Events
      #   if: failure()
      #   uses: masci/datadog@v1
      #   with:
      #     api-key: ${{ secrets.DD_API_KEY }}
      #     api-url: https://us3.datadoghq.com
      #     events: |
      #       - title: "Failed building Foo"
      #         text: "Branch ${{ github.head_ref }} failed to build"
      #         alert_type: "error"
      #         host: ${{ github.repository_owner }}
      #         tags:
      #           - "project:${{ github.repository }}"