name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Datadog Agent
        uses: DataDog/agent-github-action@v1
        with:
            api_key: ${{ secrets.DD_API_KEY }}
            datadog_site: "us3.datadoghq.com"

      - uses: actions/checkout@v2
      - name: test
        run: |
          pip install -U pytest
          pip install -U ddtrace
          DD_ENV=ci DD_SERVICE=NICK-TEST pytest --ddtrace

      - name: Build count
        uses: masci/datadog@v1
        with:
          api-key:  ${{ secrets.DD_API_KEY }}
          api-url: "us3.datadoghq.com"
          metrics: |
            - type: "count"
              name: "test.runs.count"
              value: 1.0
              host: ${{ github.repository_owner }}
              tags:
                - "project:${{ github.repository }}"
                - "branch:${{ github.head_ref }}"
          
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.